# Custom Language File for Launcher Customizer

[ejs.app]
title = "Kowa Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://youtube.com/@kowazalski"
mediaDiscordURL = "https://discord.gg/kowamc"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BEM-VINDO A KOWAMC!"
welcomeDescription = "Este é o launcher recomendado para o uso na KowaMC"
welcomeDescCTA = "Em alguns clicks você já estará entrando na Kowa!"
