[ejs.landing]
updateAvailableTooltip = "Atualização Disponível"
usernamePlaceholder = "Nome de usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Não&nbsp;Essencial"
newsButton = "NOTÍCIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum Servidor Selecionado"
launchDetails = "Por favor, aguarde.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Verificando Notícias.."
newsErrorFailedSpan = "Falha ao Carregar Notícias"
newsErrorRetryButton = "Tentar Novamente"
newsErrorNoneSpan = "Sem Notícias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "LOGIN DO MINECRAFT"
loginEmailError = "* Valor Inválido"
loginEmailPlaceholder = "EMAIL OU USUÁRIO"
loginPasswordError = "* Obrigatório"
loginPasswordPlaceholder = "SENHA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "esqueceu a senha?"
loginRememberMeText = "lembrar de mim?"
loginButtonText = "ENTRAR"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Precisa de uma Conta?"
loginPasswordDisclaimer1 = "Sua senha é enviada diretamente para a Mojang e nunca é armazenada."
loginPasswordDisclaimer2 = "{appName} não é afiliado à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Login Options"
loginWithMicrosoft = "Login with Microsoft"
loginWithMojang = "Login with Mojang"
loginOffline = "Play Offline"
cancelButton = "Cancel"

[ejs.loginOffline]
cancelText = "Cancel"
subheader = "OFFLINE LOGIN"
usernameError = "* Invalid Value"
usernamePlaceholder = "CHOOSE YOUR NICKNAME"
loginButtonText = "PLAY"
disclaimer1 = "Offline mode allows you to play without authentication."
disclaimer2 = "You won't be able to play on online servers that require authentication."

[ejs.overlay]
serverSelectHeader = "Servidores Disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecione uma Conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Concluído"
tabAccountHeaderText = "Configurações de Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Add Microsoft Account"
mojangAccount = "Mojang"
addMojangAccount = "+ Add Mojang Account"
offlineAccount = "Offline"
addOfflineAccount = "+ Add Offline Account"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relacionadas ao lançamento do jogo."
gameResolutionTitle = "Resolução do Jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Executar o processo do jogo desacoplado do launcher."
launchDetachedDesc = "Se o jogo não estiver desacoplado, fechar o launcher também fechará o jogo."
tabModsHeaderText = "Configurações de Mods"
tabModsHeaderDesc = "Ative ou desative mods."
switchServerButton = "Alternar"
requiredMods = "Mods Obrigatórios"
optionalMods = "Mods Opcionais"
dropinMods = "Drop-in Mods"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para Atualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ative ou desative shaders. Observe que shaders só rodarão com desempenho em máquinas potentes. Você pode adicionar packs personalizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configurações do Java"
tabJavaHeaderDesc = "Gerencie a configuração do Java (avançado)."
memoryTitle = "Memória"
maxRAM = "RAM Máxima"
minRAM = "RAM Mínima"
memoryDesc = "O mínimo recomendado é 3 gigabytes. Definir os valores mínimo e máximo iguais pode reduzir lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável Java"
javaExecSelDialogTitle = "Selecionar Executável Java"
javaExecSelButtonText = "Escolher Arquivo"
javaExecDesc = "O executável Java é validado antes do lançamento do jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções JVM Adicionais"
jvmOptsDesc = "Opções a serem fornecidas à JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> não devem ser incluídos."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações Pré-lançamento."
allowPrereleaseDesc = "Pré-lançamentos incluem novos recursos que podem não ter sido totalmente testados ou integrados.<br>Isso sempre será verdadeiro se você estiver usando uma versão pré-lançamento."
dataDirectoryTitle = "Diretório de Dados"
selectDataDirectory = "Selecionar Diretório de Dados"
chooseFolder = "Escolher Pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalações locais do Java serão armazenados no diretório de dados.<br>Capturas de tela e mundos salvos são guardados na pasta da instância correspondente à configuração do servidor."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Veja informações e notas de versão para a versão atual."
aboutTitle = "{appName}"
stableRelease = "Versão Estável"
versionText = "Versão "
sourceGithub = "Código-fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas de Lançamento"
changelog = "Changelog"
noReleaseNotes = "Sem Notas de Lançamento"
viewReleaseNotes = "Ver Notas de Lançamento no GitHub"
launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise atualizações para o launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "O que há de novo"
updateReleaseNotes = "Notas de Atualização"

[ejs.waiting]
waitingText = "Aguardando Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"


[js.discord]
waiting = "Aguardando Cliente.."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "LOGIN"
loggingIn = "Logging In"
success = "SUCCESS"
tryAgain = "Try Again"

[js.login.error]
invalidValue = "* Invalid Value"
requiredValue = "* Required"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error occurred. See the console for details."

[js.loginOffline]
login = "PLAY"
loggingIn = "Entering"
success = "SUCCESS"
tryAgain = "Try Again"

[js.loginOffline.error]
invalidValue = "* Only letters, numbers and _ (3-16 characters)"
requiredValue = "* Required"
unknown = "Unknown Error"
unknownDesc = "An error occurred while creating the offline account."

[js.landing.launch]
pleaseWait = "Por favor, aguarde.."
failureTitle = "Erro Durante o Lançamento"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma Conta Selecionada"

[js.landing.selectedServer]
noSelection = "Nenhuma Seleção"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.systemScan]
checking = "Verificando informações do sistema.."
noCompatibleJava = "Nenhuma Instalação Java compatível encontrada"
installJavaMessage = "Para iniciar o Minecraft, você precisa de uma instalação Java x64 {major}. Gostaria que instalássemos uma cópia?"
installJava = "Instalar Java"
installJavaManually = "Instalar Manualmente"
javaDownloadPrepare = "Preparando download do Java.."
javaDownloadFailureTitle = "Erro Durante o Download do Java"
javaDownloadFailureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
javaRequired = "Java é Necessário<br>para Iniciar"
javaRequiredMessage = 'Uma instalação x64 válida do Java {major} é necessária para iniciar.<br><br>Consulte nosso <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Guia de Gerenciamento do Java</a> para instruções sobre como instalar o Java manualmente.'
javaRequiredDismiss = "Entendi"
javaRequiredCancel = "Voltar"

[js.landing.downloadJava]
findJdkFailure = "Falha ao encontrar distribuição OpenJDK."
javaDownloadCorruptedError = "O JDK baixado tem hash incorreto, o arquivo pode estar corrompido."
extractingJava = "Extraindo Java"
javaInstalled = "Java Instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Carregando informações do servidor.."
fatalError = "Erro Fatal"
unableToLoadDistributionIndex = "Não foi possível carregar uma cópia do índice de distribuição. Veja o console (CTRL + Shift + i) para mais detalhes."
pleaseWait = "Por favor, aguarde.."
errorDuringLaunchTitle = "Erro Durante o Lançamento"
seeConsoleForDetails = "Veja o console (CTRL + Shift + i) para mais detalhes."
validatingFileIntegrity = "Validando integridade dos arquivos.."
errorDuringFileVerificationTitle = "Erro Durante a Verificação de Arquivos"
downloadingFiles = "Baixando arquivos.."
errorDuringFileDownloadTitle = "Erro Durante o Download de Arquivos"
preparingToLaunch = "Preparando para iniciar.."
launchingGame = "Iniciando o jogo.."
launchWrapperNotDownloaded = "O arquivo principal, LaunchWrapper, falhou ao ser baixado corretamente. Como resultado, o jogo não pode ser iniciado.<br><br>Para corrigir este problema, desative temporariamente seu antivírus e tente lançar o jogo novamente.<br><br>Se possível, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">abra uma issue</a> e nos informe qual antivírus você usa. Entraremos em contato com eles para tentar resolver o problema."
doneEnjoyServer = "Concluído. Aproveite o servidor!"
checkConsoleForDetails = "Por favor, verifique o console (CTRL + Shift + i) para mais detalhes."

[js.landing.news]
checking = "Verificando Notícias"

[js.landing.discord]
loading = "Carregando jogo.."
joining = "Navegando para Westeros!"
joined = "Explorando o Reino!"

[js.overlay]
dismiss = "Fechar"

[js.settings.fileSelectors]
executables = "Executáveis"
allFiles = "Todos os Arquivos"

[js.settings.mstfLogin]
errorTitle = "Algo Deu Errado"
errorMessage = "A autenticação Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo Deu Errado"
errorMessage = "Logout Microsoft falhou. Por favor, tente novamente."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Selecionar Conta"
selectedButton = "Conta Selecionada &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Aviso<br>Esta é sua Última Conta"
lastAccountWarningMessage = "Para usar o launcher você deve estar logado em pelo menos uma conta. Você precisará fazer login novamente depois.<br><br>Tem certeza de que deseja sair?"
confirmButton = "Tenho Certeza"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nome de usuário"
uuid = "UUID"
selectAccount = "Selecionar Conta"
selectedAccount = "Conta Selecionada ✓"
logout = "Sair"

[js.settings.dropinMods]
removeButton = "Remover"
deleteFailedTitle = "Falha ao Excluir<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Certifique-se de que o arquivo não está em uso e tente novamente."
failedToggleTitle = "Falha ao Alternar<br>Um ou Mais Drop-in Mods"
okButton = "Ok"

[js.settings.serverListing]
mainServer = "Servidor Principal"

[js.settings.java]
selectedJava = "Selecionado: Java {version} ({vendor})"
invalidSelection = "Seleção Inválida"
requiresJava = "Requer Java {major} x64."
availableOptions = "Opções Disponíveis para Java {major} (VM HotSpot)"

[js.settings.about]
preReleaseTitle = "Pré-lançamento"
stableReleaseTitle = "Versão Estável"
releaseNotesFailed = "Falha ao carregar notas de lançamento."

[js.settings.updates]
newReleaseTitle = "Nova Versão Disponível"
newPreReleaseTitle = "Nova Pré-lançamento Disponível"
downloadingButton = "Baixando.."
downloadButton = 'Baixar do GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Feche o launcher e execute o dmg para atualizar.</span>'
latestVersionTitle = "Você Está Usando a Versão Mais Recente"
checkForUpdatesButton = "Verificar Atualizações"
checkingForUpdatesButton = "Verificando Atualizações.."

[js.settings.msftLogin]
errorTitle = "Falha no Login Microsoft"
errorMessage = "Não foi possível autenticar sua conta Microsoft. Por favor, tente novamente."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erro Fatal: Incapaz de Carregar o Índice de Distribuição"
fatalErrorMessage = "Não foi possível estabelecer conexão com nossos servidores para baixar o índice de distribuição. Não havia cópias locais disponíveis para carregar. <br><br>O índice de distribuição é um arquivo essencial que fornece as informações mais recentes dos servidores. O launcher não pode iniciar sem ele. Certifique-se de estar conectado à internet e reinicie a aplicação."
closeButton = "Fechar"

[js.uibinder.validateAccount]
failedMessageTitle = "Falha ao Atualizar Login"
failedMessage = "Não conseguimos atualizar o login de <strong>{account}</strong>. Por favor, selecione outra conta ou faça login novamente."
failedMessageSelectAnotherAccount = "Não conseguimos atualizar o login de <strong>{account}</strong>. Por favor, faça login novamente."
loginButton = "Login"
selectAnotherAccountButton = "Selecionar Outra Conta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações..."
installNowButton = "Instalar Agora"
checkForUpdatesButton = "Verificar Atualizações"

[js.auth.microsoft.error]
noProfileTitle = "Erro Durante o Login:<br>Perfil Não Configurado"
noProfileDesc = "Sua conta Microsoft ainda não tem um perfil Minecraft configurado. Se você adquiriu o jogo recentemente ou o resgatou pelo Xbox Game Pass, é preciso configurar seu perfil em <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Se você ainda não comprou o jogo, você pode adquiri-lo em <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erro Durante o Login:<br>Sem Conta Xbox"
noXboxAccountDesc = "Sua conta Microsoft não tem uma conta Xbox associada."
xblBannedTitle = "Erro Durante o Login:<br>Xbox Live Indisponível"
xblBannedDesc = "Sua conta Microsoft é de um país onde o Xbox Live não está disponível ou é bloqueado."
under18Title = "Erro Durante o Login:<br>Aprovação Parental Necessária"
under18Desc = "Contas de usuários com menos de 18 anos devem ser adicionadas a uma Família por um adulto."
unknownTitle = "Erro Desconhecido Durante o Login"
unknownDesc = "Ocorreu um erro desconhecido. Veja o console para detalhes."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erro Interno:<br>Método Não Permitido"
methodNotAllowedDesc = "Método não permitido. Por favor, reporte este erro."
notFoundTitle = "Erro Interno:<br>Não Encontrado"
notFoundDesc = "O endpoint de autenticação não foi encontrado. Por favor, reporte este problema."
accountMigratedTitle = "Erro Durante o Login:<br>Conta Migrada"
accountMigratedDesc = "Você tentou fazer login com uma conta migrada. Tente novamente usando o email da conta como nome de usuário."
invalidCredentialsTitle = "Erro Durante o Login:<br>Credenciais Inválidas"
invalidCredentialsDesc = "O email ou senha inseridos estão incorretos. Por favor, tente novamente."
tooManyAttemptsTitle = "Erro Durante o Login:<br>Muitas Tentativas"
tooManyAttemptsDesc = "Houve muitas tentativas de login com esta conta recentemente. Por favor, tente novamente mais tarde."
invalidTokenTitle = "Erro Durante o Login:<br>Token Inválido"
invalidTokenDesc = "O token de acesso fornecido é inválido."
tokenHasProfileTitle = "Erro Durante o Login:<br>Token Já Tem Perfil"
tokenHasProfileDesc = "O token de acesso já possui um perfil atribuído. A seleção de perfis ainda não foi implementada."
credentialsMissingTitle = "Erro Durante o Login:<br>Credenciais Ausentes"
credentialsMissingDesc = "Nome de usuário/senha não foi enviado ou a senha tem menos de 3 caracteres."
invalidSaltVersionTitle = "Erro Durante o Login:<br>Versão de Salt Inválida"
invalidSaltVersionDesc = "Versão de salt inválida."
unsupportedMediaTypeTitle = "Erro Interno:<br>Tipo de Mídia Não Suportado"
unsupportedMediaTypeDesc = "Tipo de mídia não suportado. Por favor, reporte este erro."
accountGoneTitle = "Erro Durante o Login:<br>Conta Migrada"
accountGoneDesc = "A conta foi migrada para uma conta Microsoft. Por favor, faça login com a Microsoft."
unreachableTitle = "Erro Durante o Login:<br>Inacessível"
unreachableDesc = "Incapaz de alcançar os servidores de autenticação. Certifique-se de que estão online e que você está conectado à internet."
gameNotPurchasedTitle = "Erro Durante o Login:<br>Jogo Não Comprado"
gameNotPurchasedDesc = "A conta que você está tentando usar não comprou uma cópia do Minecraft. Você pode comprar em <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erro Desconhecido Durante o Login"
unknownErrorDesc = "Ocorreu um erro desconhecido. Veja o console para detalhes."
